---
- hosts: all
  vars:
    - ansible_ssh_pipelining: false
    - dumpall_flat_mode: true
    - dumpall_guest_destination: /tmp/ansible.all
    - dumpall_host_destination: "/tmp/dumpvars-{{ inventory_hostname }}"

  tasks:
    - name: Dump all vars
      template: src=dumpvars.j2 dest={{ dumpall_guest_destination }}

    - name: Retrieve dumpfile
      fetch: "src={{ dumpall_guest_destination }} dest={{ dumpall_host_destination }} flat={{ dumpall_flat_mode }}"
      when: "dumpall_host_destination is defined"

    - name: Remove dumpfile on the guest
      file: path={{ dumpall_guest_destination }} state=absent
      when: "dumpall_host_destination is defined"
