---
version: ""

formatter: "markdown table"

header-from: "main.tf"
footer-from: ""

sections:
  hide: []
  show: []

  hide-all: false  # deprecated in v0.13.0, removed in v0.15.0
  show-all: false  # deprecated in v0.13.0, removed in v0.15.0

content: |-
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->

    {{ .Content }}

    <!-- END_TF_DOCS -->


sort:
  enabled: true
  by: name

settings:
  anchor: false
  color: true
  default: true
  description: false
  escape: true
  html: false
  indent: 3
  required: true
  sensitive: false
  type: false
