---
# Ansible requirements

collections:
  - name: ansible.posix  # for authorized_key
  - name: community.general  # Proxmox inventory
  # - name: devsec.hardening
  - name: amazon.aws  # for AWS inventory

roles:
  - name: ironicbadger.ansible_role_proxmox_nag_removal
