---
# General settings
ansible_python_interpreter: /usr/bin/python3

# vault_ variables are defined in vault.yml
my_username: "{{ vault_my_username }}"
my_groupname: "{{ my_username }}"
my_gh_username: "{{ vault_my_gh_username }}"  # github
my_password: "{{ vault_my_password }}"

ansible_username: "{{ vault_ansible_username }}"
ansible_groupname: "{{ ansible_username }}"

# bootstrap
useful_programs:
  - bash-completion
  - curl
  - figlet
  - git
  - htop
  - less
  - nano
  - ncdu
  - net-tools
  - python3
  - sudo
  - tmux
  - wget

vm_specific_programs:
  - haveged
  - qemu-guest-agent

general_aliases:
  - g="git"

# geerlingguy.security
security_ssh_allowed_users:
  - "{{ my_username }}"
  - "{{ ansible_username }}"

security_sudoers_passwordless:
  - "{{ ansible_username }}"
