---
- name: Change my password
  hosts: all
  become: true
  vars_files:
    - ../vars/vault.yml

  tasks:
    - name: Change my password
      ansible.builtin.user:
        name: "{{ my_username }}"
        update_password: always
        password: "{{ my_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
      no_log: true
