---

name: Generate dependabot.yml

on:
  push:
    paths:
      - .github/dependabot.template.yml
      - .github/workflows/generate_dependabot.yml

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate dependabot.yml
        uses: Makeshift/generate-dependabot-glob-action@v1

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
