---
# Runs ansible-lint and yamllint

name: Linting

on: [push, pull_request]

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint .
