---
# Runs ansible-lint and yamllint

name: Linting

on: [push, pull_request]

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.12'

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint .
