---
name: Generate terraform docs

on:
  # push:
  #   paths:
  #     - "terraform/**.tf"
  #     - .github/workflows/terraform-docs.yml
  # pull_request:
  #   paths:
  #     - "terraform/**.tf"
  #     - .github/workflows/terraform-docs.yml

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Install tfvar and generate example tfvars file
        run: |
          curl -sL https://github.com/shihanng/tfvar/releases/latest/download/tfvar_linux_amd64.tar.gz \
            | tar xz -C . tfvar
          ./tfvar terraform/ > terraform/terraform.tfvars.example
          git add terraform/terraform.tfvars.example

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@v0.11.0
        with:
          working-dir: terraform/
          output-file: README.md
          config-file: .terraform-docs.yml
          git-push: "true"
