---
name: Generate terraform docs

on:
  push:
    paths:
      - "terraform/**.tf"
      - .github/workflows/terraform-docs.yml
  pull_request:
    paths:
      - "terraform/**.tf"
      - .github/workflows/terraform-docs.yml

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: main

      - name: Install tfvar and generate example tfvars file
        run: |
          curl -sL https://github.com/shihanng/tfvar/releases/latest/download/tfvar_linux_amd64.tar.gz \
            | tar xz -C . tfvar
          for dir in aws oci proxmox; do
            ./tfvar terraform/$dir --ignore-default > terraform/$dir/terraform.tfvars.example
          done
          git add terraform/

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c # v1.4.1
        with:
          working-dir: terraform/aws,terraform/oci,terraform/proxmox
          output-file: README.md
          config-file: .terraform-docs.yml
          git-push: "true"
