---
name: Generate terraform docs

on:
  push:
    paths:
      - "terraform/**.tf"
      - .github/workflows/terraform-docs.yml
  pull_request:
    paths:
      - "terraform/**.tf"
      - .github/workflows/terraform-docs.yml

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          ref: main

      - name: Install tfvar and generate example tfvars file
        run: |
          curl -sL https://github.com/shihanng/tfvar/releases/latest/download/tfvar_linux_amd64.tar.gz \
            | tar xz -C . tfvar
          for dir in aws oci proxmox; do
            ./tfvar terraform/$dir --ignore-default > terraform/$dir/terraform.tfvars.example
          done
          git add terraform/

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@aeae0038ed47a547e0c0fca5c059d3335f48fb25 # v1.3.0
        with:
          working-dir: terraform/aws,terraform/oci,terraform/proxmox
          output-file: README.md
          config-file: .terraform-docs.yml
          git-push: "true"
