---

name: Terraform security scan

on:
  push:
    paths:
      - "terraform/**.tf"
      - .github/workflows/tf_sec_scan.yml
  pull_request:
    paths:
      - "terraform/**.tf"
      - .github/workflows/tf_sec_scan.yml

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v3.0.0
        with:
          tfsec_actions_comment: true
          tfsec_actions_working_dir: ./terraform
